### ISSUE TITLE
Header fail at 12

### ISSUE THREAD

**Issue by eeevanbbb** [trishume/wikicrush#1]
Hey there!

I'm trying to run wikicrush on the latest simple english wikipedia dump, but I'm getting a runtime error between the `index.bin` and `indexbi.bin` steps. (Deleting the 16 byte `indexbi.bin` and running it again produces the same error.) The other files seem to generate fine. Here's the error:

```
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby gen/doublelink.rb data/index.bin data/indexbi.bin
...... (elapsed: 0s)
gen/doublelink.rb:38:in `page_links': Header fail at 12 (RuntimeError)
	from gen/doublelink.rb:53:in `bidirectional?'
	from gen/doublelink.rb:26:in `block in do_page'
	from gen/doublelink.rb:26:in `each'
	from gen/doublelink.rb:26:in `partition'
	from gen/doublelink.rb:26:in `do_page'
	from gen/doublelink.rb:18:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:110:in `block (3 levels) in run_with_length'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress.rb:80:in `step'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/class_methods.rb:25:in `step'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:109:in `block (2 levels) in run_with_length'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:108:in `times'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:108:in `each'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:108:in `block in run_with_length'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/class_methods.rb:16:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:107:in `run_with_length'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:70:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:45:in `method_missing'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/with_progress.rb:12:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/progress-3.2.2/lib/progress/enumerable.rb:26:in `with_progress'
	from gen/doublelink.rb:17:in `run'
	from gen/doublelink.rb:64:in `<main>'
rake aborted!
Command failed with status (1): [/System/Library/Frameworks/Ruby.framework/...]
/Volumes/Evan's Hard Drive/Wikipedia-Nonsense/wikicrush/Rakefile:39:in `block in <top (required)>'
/Library/Ruby/Gems/2.0.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
Tasks: TOP => data/indexbi.bin
(See full trace by running task with --trace)
```

Looks like it's having trouble reading the `index.bin` header. Any idea why?

**Comment by trishume** [comment]
Hmmm, I'm not sure, it might be a new edge case in Wikipedia that wasn't there before, or I might have just monkeyed around with the program since I last ran it. I'll try and get around to debugging this soon, in the mean time you can use the download link for the Feb 2015.

**Comment by trishume** [comment]
Oh I think I know why it broke for you but worked fine for me last time. I used the new Nim version of doublelink that is waaaaaaay faster. I forget how long the Ruby version takes but it might be as high as 24 hours. The Nim version I think takes less than 2.

You should be able to solve your problem in the short term by installing Nim and using that version. I'll try and fix the Ruby version though.

**Comment by trishume** [comment]
That was indeed the issue, I updated the Ruby version, but I still recommend you install Nim.

**Comment by eeevanbbb** [comment]
Thanks!

I installed Nim, although I'm still getting a warning about installing Nim to speed up the process.

Also, there seems to be a cascading OB1 error with the byte offsets. When I load the `indexbi.bin` file into an Int32 array (in Python), the first article ("April" in the simple english wiki) is where it should be, but each following article seems to be off by (n-1)*4 bytes (where n is the index of the article, "April" being 1.) Specifically, the offset for the next article ("August") is 4 bytes (1 spot in the Int32 array) ahead of where it should be (so it's pointing to the second Int of the header, rather than the 0 slot). The offset for the next article ("Art") is 8 bytes (2 spots) ahead, and so on. The number of links encoded in the page headers seems to be correct, however. Any idea what's going on?

**Comment by trishume** [comment]
I created a new issue (see #2) for the off by one error, I'll try and look at it tomorrow. Please put any further discussion there.

I just pushed a fix for the fact that you are still getting the warning. It's because I accidentally comitted the code I used to disable the nim version to test the ruby version. See https://github.com/trishume/wikicrush/commit/e84ce7cf8aac998af6a59e86ac6366488552f991
