### ISSUE TITLE
Possible off by one error

### ISSUE THREAD

**Issue by trishume** [trishume/wikicrush#2]
From @eeevanbbb in #1 

> Also, there seems to be a cascading OB1 error with the byte offsets. When I load the indexbi.bin file into an Int32 array (in Python), the first article ("April" in the simple english wiki) is where it should be, but each following article seems to be off by (n-1)*4 bytes (where n is the index of the article, "April" being 1.) Specifically, the offset for the next article ("August") is 4 bytes (1 spot in the Int32 array) ahead of where it should be (so it's pointing to the second Int of the header, rather than the 0 slot). The offset for the next article ("Art") is 8 bytes (2 spots) ahead, and so on. The number of links encoded in the page headers seems to be correct, however. Any idea what's going on?

I think this probably also has to do with the recent addition of one field I did. Almost definitely a real bug and an easy fix. I did not test this new metadata field enough.

**Comment by trishume** [comment]
@eeevanbbb it was a bug in the Ruby version, should be fixed now. I still recommend the Nim version though.

**Comment by eeevanbbb** [comment]
Just tried the nim version, works great and fast. Thanks for the quick fix!
